# (c) https://github.com/MontiCore/monticore

name: Monti Gradle Build & Deploy

concurrency: # run this test workflow only once per "branch"
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push: # run this test pipeline on every push
    paths-ignore:
      - "*.md"
    branches: [ $default-branch ] # Only run on the default branch

env:
  GRADLE_VERSION: 7.4 # Gradle version used
  GRADLE_CLI_OPTS: "-Pci --build-cache " # CLI option passed to Gradle
  GRADLE_BUILD_ACTION_CACHE_KEY_JOB: "test-cache-${{ github.head_ref }}.${{ github.sha }}"

permissions:
  contents: read

jobs:
    deploy-snapshot:
        runs-on: ubuntu-20.04
        permissions:
          packages: write
        steps:
          - name: Checkout project sources
            uses: actions/checkout@v3
          - name: Gradle publish
            uses: gradle/actions/setup-gradle@v3
            with:
              gradle-version: ${{env.GRADLE_VERSION}}
              arguments: publish  ${{env.GRADLE_CLI_OPTS}}  -PmavenPassword=${{ secrets.SE_NEXUS_PASSWORD }} -PmavenUser=${{ secrets.SE_NEXUS_USER }}
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
    # Trigger GitHub downstream projects (without reporting the pipeline result)
    trigger-github-downstream:
      needs: [ deploy-snapshot ]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          project: [ "MontiCore/cd4analysis", "MontiCore/feature-diagram", "MontiCore/xml", "MontiCore/json", "MontiCore/ucd", "MontiCore/automaton" ]
      steps:
        - name: Trigger ${{ matrix.project }}
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.DOWNSTREAM_PAT }}
            repository: ${{ matrix.project }}
            event-type: trigger_after_upstream_deploy