# (c) https://github.com/MontiCore/monticore
name: "Test Callable"

on:
  workflow_call:
    inputs:
      a:
        description: "A(n) input"
        type: string
        required: false

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: A
        run: echo "inputs: ${{ inputs }}"
      - name: PG
        run: echo "github.sha: ${{ github.sha }}"
      - name: P
        run: echo "pull_request: ${{ github.event.pull_request.number }}"
