on:
    workflow_call:
        inputs:
            projects:
                # An example with-usage can look like the following
                # projects: toJSON([ "MontiCore/cd4analysis", "MontiCore/feature-diagram", "MontiCore/xml", "MontiCore/json", "MontiCore/ucd", "MontiCore/automaton" ])
                description: 'The JSON-projects to trigger'
                type: string
                required: true
        secrets:
            DOWNSTREAM_PAT:
                required: true

jobs:
    # Run the MontiVerse pipeline (tests this change on a suite of projects)
    trigger-github-downstream:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            project:  ${{ fromJSON(inputs.projects) }}
      steps:
        - name: Trigger ${{ matrix.project }}
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.DOWNSTREAM_PAT }}
            repository: ${{ matrix.project }}
            event-type: trigger_after_upstream_deploy